name: bookly_mvvm
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  dartz: ^0.10.1
  dio: ^5.4.2+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  get_it: ^7.6.8
  go_router: ^13.2.2
  percent_indicator: ^4.2.3
  shared_preferences: ^2.2.2
  skeletonizer: ^1.4.3

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
    - assets/fonts/
  fonts:
    - family: 'GT Sectra Fine'
      fonts:
        - asset: 'assets/fonts/GT Sectra Fine Regular.ttf'

  uses-material-design: true
